<a href="https://colab.research.google.com/github/LeightonEstrada/2021_BD-ML_Python_Tutorials/blob/main/Tut07/07%20M3%20Tutoria%2011-06-2021%20Ejercicios%20Arrays%201D%202D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Diplomatura BD&ML UTEC 2021

# Tutoría de Reforzamiento Viernes 11-06-2021

## Tutor: Leighton Estrada

## Ejercicios con Arrays

### Importamos libreria numpy

In [1]:
import numpy as np

### range

In [2]:
range(10)

range(0, 10)

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
range(1,26)

range(1, 26)

In [5]:
np.array(range(1,26))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

### asarray

In [6]:
a = [1, 2]
a

[1, 2]

In [7]:
np.asarray(a)

array([1, 2])

In [8]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [9]:
b = np.array((1, 2), dtype=np.float32)
b

array([1., 2.], dtype=float32)

### shape

In [10]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [11]:
np.array([1, 2, 3, 4]).shape

(4,)

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2, 3)).shape

(2, 3)

In [14]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.zeros((2, 3, 4)).shape

(2, 3, 4)

In [16]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((4, 3, 2)).shape

(4, 3, 2)

### reshape

In [18]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [19]:
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

### ravel

In [20]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [22]:
np.shape(x)

(2, 3)

In [23]:
np.shape(np.ravel(x))

(6,)

### flatten

In [24]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [25]:
a.flatten()

array([1, 2, 3, 4])

### diagonal

In [26]:
a = np.arange(4).reshape(2,2)

In [27]:
np.diagonal(a)

array([0, 3])

In [28]:
a.diagonal()

array([0, 3])

### broadcast_to

In [29]:
x = np.array([1, 2, 3])

In [30]:
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Ejercicios 1-D


#### Opcional
#### Importando el modulo as_strided

In [31]:
from numpy.lib.stride_tricks import as_strided

### Ejercicio 1
#### Slice first 3 elements


In [32]:
np.asarray(range(1,26))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
np.asarray(range(1,26)).dtype

dtype('int64')

In [34]:
np.asarray(range(1,26), np.int8)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int8)

In [35]:
np.asarray(range(1,26), np.int8).shape

(25,)

In [36]:
np.asarray(range(1,26), np.int8).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [37]:
np.asarray(range(1,26), np.int8).reshape(5,5).shape

(5, 5)

In [38]:
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [39]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [40]:
x[0,:3] #fila 0 #columnas 3 primeros elementos

array([1, 2, 3], dtype=int8)

#### Opcional

In [41]:
as_strided(x, shape=(3,), strides=(1,))

array([1, 2, 3], dtype=int8)

### Ejercicio 2
#### Slice first 8 elements

In [42]:
np.asarray(range(1,26), np.int8).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [43]:
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [44]:
x[0,:8]

array([1, 2, 3, 4, 5], dtype=int8)

#### Opcional

In [45]:
as_strided(x, shape=(8,), strides=(1,))

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

### Ejercicio 3
#### Flatten a 2D array

In [46]:
x = np.asarray(range(1,26), np.int16).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int16)

In [47]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

#### Opcional

In [48]:
as_strided(x, shape=(25,), strides=(2,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

### Ejercicio 4
#### Skip every other element

In [49]:
x = np.asarray(range(1,26), np.int8).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [50]:
x[0,::2]

array([1, 3, 5], dtype=int8)

#### Opcional

In [51]:
as_strided(x, shape=(3,), strides=(2,))

array([1, 3, 5], dtype=int8)

### Ejercicio 5
#### Slice first column

In [52]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)

In [53]:
x[:4,0]

array([ 1,  6, 11, 16])

#### Opcional

In [54]:
as_strided(x, shape=(4,), strides=(40,))

array([ 1,  6, 11, 16])

### Ejercicio 6
#### Slice a diagonal

In [55]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)

In [56]:
x.diagonal()

array([ 1,  7, 13, 19, 25])

#### Opcional

In [57]:
as_strided(x, shape=(5,), strides=(48,))

array([ 1,  7, 13, 19, 25])

### Ejercicio 7
#### Repeat the first element

In [58]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)

In [59]:
np.broadcast_to(x[0,0], (5,))

array([1, 1, 1, 1, 1])

#### Opcional

In [60]:
as_strided(x, shape=(5,), strides=(0,))

array([1, 1, 1, 1, 1])

### Ejercicio 8
#### Simple 2D slicing

In [61]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)

In [62]:
x[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

#### Opcional

In [63]:
as_strided(x, shape=(3,4), strides=(40,8))

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

### Ejercicio 9
#### Simple 2D slicing

In [64]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)

In [65]:
x[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

### Ejercicio 10
#### Sparse slicing

In [66]:
x = np.asarray(range(1,26), np.int64).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
x[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

#### Opcional

In [68]:
as_strided(x, shape=(3,3), strides=(80,16))

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

### Ejercicio 11
#### Transpose a 2D array

In [69]:
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [70]:
x[:3,:3].T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

#### Opcional

In [71]:
as_strided(x, shape=(3,3), strides=(1,5))

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

### Ejercicio 12
#### Repeat the first column 4 times

In [72]:
x = np.asarray(range(1,26), np.int32).reshape(5,5)

In [73]:
np.broadcast_to(x[:,0,None], (5,4))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

#### Opcional

In [74]:
as_strided(x, shape=(5,4), strides=(20,0))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

### Ejercicio 13
#### Reshape 1D array to 2D array

In [75]:
x = np.asarray(range(1,13), np.int64)

In [76]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Opcional

In [77]:
as_strided(x, shape=(4,3), strides=(24,8))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

-- Fin de la Tutoría --

--Fin de la Tutoría